// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SSLCertificateChecker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("subject")]
        public Issuer Subject { get; set; }

        [JsonProperty("issuer")]
        public Issuer Issuer { get; set; }

        [JsonProperty("subjectaltname")]
        public string Subjectaltname { get; set; }

        [JsonProperty("infoAccess")]
        public Dictionary<string, Uri[]> InfoAccess { get; set; }

        [JsonProperty("ca")]
        public bool? Ca { get; set; }

        [JsonProperty("bits")]
        public long? Bits { get; set; }

        [JsonProperty("valid_from")]
        public string ValidFrom { get; set; }

        [JsonProperty("valid_to")]
        public string ValidTo { get; set; }

        [JsonProperty("serialNumber")]
        public string SerialNumber { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("isExpired")]
        public bool? IsExpired { get; set; }

        [JsonProperty("isValid")]
        public bool? IsValid { get; set; }

        [JsonProperty("daysUntilExpiry")]
        public long? DaysUntilExpiry { get; set; }

        [JsonProperty("isExpiringSoon")]
        public bool? IsExpiringSoon { get; set; }

        [JsonProperty("isSelfSigned")]
        public bool? IsSelfSigned { get; set; }
    }

    public partial class Issuer
    {
        [JsonProperty("C")]
        public string C { get; set; }

        [JsonProperty("O")]
        public string O { get; set; }

        [JsonProperty("CN")]
        public string Cn { get; set; }

        [JsonProperty("ST")]
        public string St { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
